# Generated by slice2py - DO NOT EDIT!
#

import Ice
Ice.updateModule("com.hst.boss")

# Modules:
import CommonModel_ice
import CommonService_ice

# Submodules:
from . import model
from . import service
