# Generated by slice2py - DO NOT EDIT!
#

import Ice
Ice.updateModule("com.fastonz.live.sliceprotocol.model")

# Modules:
import AppCertifyModel_ice
import AppHeartbeatModel_ice
import AppModel_ice
import ChatRecordModel_ice
import GetChatRecordModel_ice
import LiveRoomCDNModel_ice
import LiveRoomExpandModel_ice
import LiveRoomInfoModel_ice
import LiveRoomModel_ice
import LiveRoomThirdpartyPushRunModel_ice
import TokenModel_ice

# Submodules:
