# Generated by slice2py - DO NOT EDIT!
#

import Ice
Ice.updateModule("com.fastonz.fmconfctlserver")

# Modules:
import CloseRoomRequestModel_ice
import CloseRoomResponseModel_ice
import RoomControlService_ice

# Submodules:
from . import model
from . import roomControl
