# Generated by slice2py - DO NOT EDIT!
#

import Ice
Ice.updateModule("com.fastonz.live.sliceprotocol.controller")

# Modules:
import AppCertifyService_ice
import AppService_ice
import LiveRoomService_ice
import UserService_ice

# Submodules:
