# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.5
#
# <auto-generated>
#
# Generated from file `AppModel.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module com
_M_com = Ice.openModule('com')
__name__ = 'com'

# Start of module com.fastonz
_M_com.fastonz = Ice.openModule('com.fastonz')
__name__ = 'com.fastonz'

# Start of module com.fastonz.live
_M_com.fastonz.live = Ice.openModule('com.fastonz.live')
__name__ = 'com.fastonz.live'

# Start of module com.fastonz.live.sliceprotocol
_M_com.fastonz.live.sliceprotocol = Ice.openModule('com.fastonz.live.sliceprotocol')
__name__ = 'com.fastonz.live.sliceprotocol'

# Start of module com.fastonz.live.sliceprotocol.model
_M_com.fastonz.live.sliceprotocol.model = Ice.openModule('com.fastonz.live.sliceprotocol.model')
__name__ = 'com.fastonz.live.sliceprotocol.model'

if 'AppModel' not in _M_com.fastonz.live.sliceprotocol.model.__dict__:
    _M_com.fastonz.live.sliceprotocol.model.AppModel = Ice.createTempClass()
    class AppModel(object):
        def __init__(self, appId='', appType=0, desc='', address='', weight=0):
            self.appId = appId
            self.appType = appType
            self.desc = desc
            self.address = address
            self.weight = weight

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.appId)
            _h = 5 * _h + Ice.getHash(self.appType)
            _h = 5 * _h + Ice.getHash(self.desc)
            _h = 5 * _h + Ice.getHash(self.address)
            _h = 5 * _h + Ice.getHash(self.weight)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_com.fastonz.live.sliceprotocol.model.AppModel):
                return NotImplemented
            else:
                if self.appId is None or other.appId is None:
                    if self.appId != other.appId:
                        return (-1 if self.appId is None else 1)
                else:
                    if self.appId < other.appId:
                        return -1
                    elif self.appId > other.appId:
                        return 1
                if self.appType is None or other.appType is None:
                    if self.appType != other.appType:
                        return (-1 if self.appType is None else 1)
                else:
                    if self.appType < other.appType:
                        return -1
                    elif self.appType > other.appType:
                        return 1
                if self.desc is None or other.desc is None:
                    if self.desc != other.desc:
                        return (-1 if self.desc is None else 1)
                else:
                    if self.desc < other.desc:
                        return -1
                    elif self.desc > other.desc:
                        return 1
                if self.address is None or other.address is None:
                    if self.address != other.address:
                        return (-1 if self.address is None else 1)
                else:
                    if self.address < other.address:
                        return -1
                    elif self.address > other.address:
                        return 1
                if self.weight is None or other.weight is None:
                    if self.weight != other.weight:
                        return (-1 if self.weight is None else 1)
                else:
                    if self.weight < other.weight:
                        return -1
                    elif self.weight > other.weight:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_com.fastonz.live.sliceprotocol.model._t_AppModel)

        __repr__ = __str__

    _M_com.fastonz.live.sliceprotocol.model._t_AppModel = IcePy.defineStruct('::com::fastonz::live::sliceprotocol::model::AppModel', AppModel, (), (
        ('appId', (), IcePy._t_string),
        ('appType', (), IcePy._t_int),
        ('desc', (), IcePy._t_string),
        ('address', (), IcePy._t_string),
        ('weight', (), IcePy._t_int)
    ))

    _M_com.fastonz.live.sliceprotocol.model.AppModel = AppModel
    del AppModel

# End of module com.fastonz.live.sliceprotocol.model

__name__ = 'com.fastonz.live.sliceprotocol'

# End of module com.fastonz.live.sliceprotocol

__name__ = 'com.fastonz.live'

# End of module com.fastonz.live

__name__ = 'com.fastonz'

# End of module com.fastonz

__name__ = 'com'

# End of module com
