# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.5
#
# <auto-generated>
#
# Generated from file `AppServiceBandwidthModel.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module com
_M_com = Ice.openModule('com')
__name__ = 'com'

# Start of module com.fastonz
_M_com.fastonz = Ice.openModule('com.fastonz')
__name__ = 'com.fastonz'

# Start of module com.fastonz.fmserver
_M_com.fastonz.fmserver = Ice.openModule('com.fastonz.fmserver')
__name__ = 'com.fastonz.fmserver'

# Start of module com.fastonz.fmserver.model
_M_com.fastonz.fmserver.model = Ice.openModule('com.fastonz.fmserver.model')
__name__ = 'com.fastonz.fmserver.model'

if 'AppServiceBandwidthModel' not in _M_com.fastonz.fmserver.model.__dict__:
    _M_com.fastonz.fmserver.model.AppServiceBandwidthModel = Ice.createTempClass()
    class AppServiceBandwidthModel(object):
        def __init__(self, serviceID=0, serviceStatus='', serviceName='', serviceAddrs='', bandwidthRate=0, curBandwidth=0, maxBandwidth=0):
            self.serviceID = serviceID
            self.serviceStatus = serviceStatus
            self.serviceName = serviceName
            self.serviceAddrs = serviceAddrs
            self.bandwidthRate = bandwidthRate
            self.curBandwidth = curBandwidth
            self.maxBandwidth = maxBandwidth

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.serviceID)
            _h = 5 * _h + Ice.getHash(self.serviceStatus)
            _h = 5 * _h + Ice.getHash(self.serviceName)
            _h = 5 * _h + Ice.getHash(self.serviceAddrs)
            _h = 5 * _h + Ice.getHash(self.bandwidthRate)
            _h = 5 * _h + Ice.getHash(self.curBandwidth)
            _h = 5 * _h + Ice.getHash(self.maxBandwidth)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_com.fastonz.fmserver.model.AppServiceBandwidthModel):
                return NotImplemented
            else:
                if self.serviceID is None or other.serviceID is None:
                    if self.serviceID != other.serviceID:
                        return (-1 if self.serviceID is None else 1)
                else:
                    if self.serviceID < other.serviceID:
                        return -1
                    elif self.serviceID > other.serviceID:
                        return 1
                if self.serviceStatus is None or other.serviceStatus is None:
                    if self.serviceStatus != other.serviceStatus:
                        return (-1 if self.serviceStatus is None else 1)
                else:
                    if self.serviceStatus < other.serviceStatus:
                        return -1
                    elif self.serviceStatus > other.serviceStatus:
                        return 1
                if self.serviceName is None or other.serviceName is None:
                    if self.serviceName != other.serviceName:
                        return (-1 if self.serviceName is None else 1)
                else:
                    if self.serviceName < other.serviceName:
                        return -1
                    elif self.serviceName > other.serviceName:
                        return 1
                if self.serviceAddrs is None or other.serviceAddrs is None:
                    if self.serviceAddrs != other.serviceAddrs:
                        return (-1 if self.serviceAddrs is None else 1)
                else:
                    if self.serviceAddrs < other.serviceAddrs:
                        return -1
                    elif self.serviceAddrs > other.serviceAddrs:
                        return 1
                if self.bandwidthRate is None or other.bandwidthRate is None:
                    if self.bandwidthRate != other.bandwidthRate:
                        return (-1 if self.bandwidthRate is None else 1)
                else:
                    if self.bandwidthRate < other.bandwidthRate:
                        return -1
                    elif self.bandwidthRate > other.bandwidthRate:
                        return 1
                if self.curBandwidth is None or other.curBandwidth is None:
                    if self.curBandwidth != other.curBandwidth:
                        return (-1 if self.curBandwidth is None else 1)
                else:
                    if self.curBandwidth < other.curBandwidth:
                        return -1
                    elif self.curBandwidth > other.curBandwidth:
                        return 1
                if self.maxBandwidth is None or other.maxBandwidth is None:
                    if self.maxBandwidth != other.maxBandwidth:
                        return (-1 if self.maxBandwidth is None else 1)
                else:
                    if self.maxBandwidth < other.maxBandwidth:
                        return -1
                    elif self.maxBandwidth > other.maxBandwidth:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_com.fastonz.fmserver.model._t_AppServiceBandwidthModel)

        __repr__ = __str__

    _M_com.fastonz.fmserver.model._t_AppServiceBandwidthModel = IcePy.defineStruct('::com::fastonz::fmserver::model::AppServiceBandwidthModel', AppServiceBandwidthModel, (), (
        ('serviceID', (), IcePy._t_int),
        ('serviceStatus', (), IcePy._t_string),
        ('serviceName', (), IcePy._t_string),
        ('serviceAddrs', (), IcePy._t_string),
        ('bandwidthRate', (), IcePy._t_int),
        ('curBandwidth', (), IcePy._t_int),
        ('maxBandwidth', (), IcePy._t_int)
    ))

    _M_com.fastonz.fmserver.model.AppServiceBandwidthModel = AppServiceBandwidthModel
    del AppServiceBandwidthModel

# End of module com.fastonz.fmserver.model

__name__ = 'com.fastonz.fmserver'

# End of module com.fastonz.fmserver

__name__ = 'com.fastonz'

# End of module com.fastonz

__name__ = 'com'

# End of module com
