# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.5
#
# <auto-generated>
#
# Generated from file `DistributePhoneGwRequestModel.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module com
_M_com = Ice.openModule('com')
__name__ = 'com'

# Start of module com.fastonz
_M_com.fastonz = Ice.openModule('com.fastonz')
__name__ = 'com.fastonz'

# Start of module com.fastonz.fmserver
_M_com.fastonz.fmserver = Ice.openModule('com.fastonz.fmserver')
__name__ = 'com.fastonz.fmserver'

# Start of module com.fastonz.fmserver.model
_M_com.fastonz.fmserver.model = Ice.openModule('com.fastonz.fmserver.model')
__name__ = 'com.fastonz.fmserver.model'

if 'CallOutPhoneUserInfo' not in _M_com.fastonz.fmserver.model.__dict__:
    _M_com.fastonz.fmserver.model.CallOutPhoneUserInfo = Ice.createTempClass()
    class CallOutPhoneUserInfo(object):
        def __init__(self, phoneNum='', userRight=0):
            self.phoneNum = phoneNum
            self.userRight = userRight

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.phoneNum)
            _h = 5 * _h + Ice.getHash(self.userRight)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_com.fastonz.fmserver.model.CallOutPhoneUserInfo):
                return NotImplemented
            else:
                if self.phoneNum is None or other.phoneNum is None:
                    if self.phoneNum != other.phoneNum:
                        return (-1 if self.phoneNum is None else 1)
                else:
                    if self.phoneNum < other.phoneNum:
                        return -1
                    elif self.phoneNum > other.phoneNum:
                        return 1
                if self.userRight is None or other.userRight is None:
                    if self.userRight != other.userRight:
                        return (-1 if self.userRight is None else 1)
                else:
                    if self.userRight < other.userRight:
                        return -1
                    elif self.userRight > other.userRight:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_com.fastonz.fmserver.model._t_CallOutPhoneUserInfo)

        __repr__ = __str__

    _M_com.fastonz.fmserver.model._t_CallOutPhoneUserInfo = IcePy.defineStruct('::com::fastonz::fmserver::model::CallOutPhoneUserInfo', CallOutPhoneUserInfo, (), (
        ('phoneNum', (), IcePy._t_string),
        ('userRight', (), IcePy._t_int)
    ))

    _M_com.fastonz.fmserver.model.CallOutPhoneUserInfo = CallOutPhoneUserInfo
    del CallOutPhoneUserInfo

if '_t_CallOutPhoneUserInfoList' not in _M_com.fastonz.fmserver.model.__dict__:
    _M_com.fastonz.fmserver.model._t_CallOutPhoneUserInfoList = IcePy.defineSequence('::com::fastonz::fmserver::model::CallOutPhoneUserInfoList', (), _M_com.fastonz.fmserver.model._t_CallOutPhoneUserInfo)

if 'DistributePhoneGwRequestModel' not in _M_com.fastonz.fmserver.model.__dict__:
    _M_com.fastonz.fmserver.model.DistributePhoneGwRequestModel = Ice.createTempClass()
    class DistributePhoneGwRequestModel(object):
        def __init__(self, roomID=0, uerID=0, serviceAppID=0, callOutUserInfo=None):
            self.roomID = roomID
            self.uerID = uerID
            self.serviceAppID = serviceAppID
            self.callOutUserInfo = callOutUserInfo

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.roomID)
            _h = 5 * _h + Ice.getHash(self.uerID)
            _h = 5 * _h + Ice.getHash(self.serviceAppID)
            if self.callOutUserInfo:
                for _i0 in self.callOutUserInfo:
                    _h = 5 * _h + Ice.getHash(_i0)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_com.fastonz.fmserver.model.DistributePhoneGwRequestModel):
                return NotImplemented
            else:
                if self.roomID is None or other.roomID is None:
                    if self.roomID != other.roomID:
                        return (-1 if self.roomID is None else 1)
                else:
                    if self.roomID < other.roomID:
                        return -1
                    elif self.roomID > other.roomID:
                        return 1
                if self.uerID is None or other.uerID is None:
                    if self.uerID != other.uerID:
                        return (-1 if self.uerID is None else 1)
                else:
                    if self.uerID < other.uerID:
                        return -1
                    elif self.uerID > other.uerID:
                        return 1
                if self.serviceAppID is None or other.serviceAppID is None:
                    if self.serviceAppID != other.serviceAppID:
                        return (-1 if self.serviceAppID is None else 1)
                else:
                    if self.serviceAppID < other.serviceAppID:
                        return -1
                    elif self.serviceAppID > other.serviceAppID:
                        return 1
                if self.callOutUserInfo is None or other.callOutUserInfo is None:
                    if self.callOutUserInfo != other.callOutUserInfo:
                        return (-1 if self.callOutUserInfo is None else 1)
                else:
                    if self.callOutUserInfo < other.callOutUserInfo:
                        return -1
                    elif self.callOutUserInfo > other.callOutUserInfo:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_com.fastonz.fmserver.model._t_DistributePhoneGwRequestModel)

        __repr__ = __str__

    _M_com.fastonz.fmserver.model._t_DistributePhoneGwRequestModel = IcePy.defineStruct('::com::fastonz::fmserver::model::DistributePhoneGwRequestModel', DistributePhoneGwRequestModel, (), (
        ('roomID', (), IcePy._t_int),
        ('uerID', (), IcePy._t_int),
        ('serviceAppID', (), IcePy._t_int),
        ('callOutUserInfo', (), _M_com.fastonz.fmserver.model._t_CallOutPhoneUserInfoList)
    ))

    _M_com.fastonz.fmserver.model.DistributePhoneGwRequestModel = DistributePhoneGwRequestModel
    del DistributePhoneGwRequestModel

# End of module com.fastonz.fmserver.model

__name__ = 'com.fastonz.fmserver'

# End of module com.fastonz.fmserver

__name__ = 'com.fastonz'

# End of module com.fastonz

__name__ = 'com'

# End of module com
