# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.5
#
# <auto-generated>
#
# Generated from file `FrontStartModel.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module com
_M_com = Ice.openModule('com')
__name__ = 'com'

# Start of module com.fastonz
_M_com.fastonz = Ice.openModule('com.fastonz')
__name__ = 'com.fastonz'

# Start of module com.fastonz.fmserver
_M_com.fastonz.fmserver = Ice.openModule('com.fastonz.fmserver')
__name__ = 'com.fastonz.fmserver'

# Start of module com.fastonz.fmserver.model
_M_com.fastonz.fmserver.model = Ice.openModule('com.fastonz.fmserver.model')
__name__ = 'com.fastonz.fmserver.model'

if 'FrontStartModel' not in _M_com.fastonz.fmserver.model.__dict__:
    _M_com.fastonz.fmserver.model.FrontStartModel = Ice.createTempClass()
    class FrontStartModel(object):
        def __init__(self, localNodeID='', localNodeName='', parentNodeID='', parentNodeName='', parentCheckCode='', parentSrvAddr='', parentStatus=0, result=0):
            self.localNodeID = localNodeID
            self.localNodeName = localNodeName
            self.parentNodeID = parentNodeID
            self.parentNodeName = parentNodeName
            self.parentCheckCode = parentCheckCode
            self.parentSrvAddr = parentSrvAddr
            self.parentStatus = parentStatus
            self.result = result

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.localNodeID)
            _h = 5 * _h + Ice.getHash(self.localNodeName)
            _h = 5 * _h + Ice.getHash(self.parentNodeID)
            _h = 5 * _h + Ice.getHash(self.parentNodeName)
            _h = 5 * _h + Ice.getHash(self.parentCheckCode)
            _h = 5 * _h + Ice.getHash(self.parentSrvAddr)
            _h = 5 * _h + Ice.getHash(self.parentStatus)
            _h = 5 * _h + Ice.getHash(self.result)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_com.fastonz.fmserver.model.FrontStartModel):
                return NotImplemented
            else:
                if self.localNodeID is None or other.localNodeID is None:
                    if self.localNodeID != other.localNodeID:
                        return (-1 if self.localNodeID is None else 1)
                else:
                    if self.localNodeID < other.localNodeID:
                        return -1
                    elif self.localNodeID > other.localNodeID:
                        return 1
                if self.localNodeName is None or other.localNodeName is None:
                    if self.localNodeName != other.localNodeName:
                        return (-1 if self.localNodeName is None else 1)
                else:
                    if self.localNodeName < other.localNodeName:
                        return -1
                    elif self.localNodeName > other.localNodeName:
                        return 1
                if self.parentNodeID is None or other.parentNodeID is None:
                    if self.parentNodeID != other.parentNodeID:
                        return (-1 if self.parentNodeID is None else 1)
                else:
                    if self.parentNodeID < other.parentNodeID:
                        return -1
                    elif self.parentNodeID > other.parentNodeID:
                        return 1
                if self.parentNodeName is None or other.parentNodeName is None:
                    if self.parentNodeName != other.parentNodeName:
                        return (-1 if self.parentNodeName is None else 1)
                else:
                    if self.parentNodeName < other.parentNodeName:
                        return -1
                    elif self.parentNodeName > other.parentNodeName:
                        return 1
                if self.parentCheckCode is None or other.parentCheckCode is None:
                    if self.parentCheckCode != other.parentCheckCode:
                        return (-1 if self.parentCheckCode is None else 1)
                else:
                    if self.parentCheckCode < other.parentCheckCode:
                        return -1
                    elif self.parentCheckCode > other.parentCheckCode:
                        return 1
                if self.parentSrvAddr is None or other.parentSrvAddr is None:
                    if self.parentSrvAddr != other.parentSrvAddr:
                        return (-1 if self.parentSrvAddr is None else 1)
                else:
                    if self.parentSrvAddr < other.parentSrvAddr:
                        return -1
                    elif self.parentSrvAddr > other.parentSrvAddr:
                        return 1
                if self.parentStatus is None or other.parentStatus is None:
                    if self.parentStatus != other.parentStatus:
                        return (-1 if self.parentStatus is None else 1)
                else:
                    if self.parentStatus < other.parentStatus:
                        return -1
                    elif self.parentStatus > other.parentStatus:
                        return 1
                if self.result is None or other.result is None:
                    if self.result != other.result:
                        return (-1 if self.result is None else 1)
                else:
                    if self.result < other.result:
                        return -1
                    elif self.result > other.result:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_com.fastonz.fmserver.model._t_FrontStartModel)

        __repr__ = __str__

    _M_com.fastonz.fmserver.model._t_FrontStartModel = IcePy.defineStruct('::com::fastonz::fmserver::model::FrontStartModel', FrontStartModel, (), (
        ('localNodeID', (), IcePy._t_string),
        ('localNodeName', (), IcePy._t_string),
        ('parentNodeID', (), IcePy._t_string),
        ('parentNodeName', (), IcePy._t_string),
        ('parentCheckCode', (), IcePy._t_string),
        ('parentSrvAddr', (), IcePy._t_string),
        ('parentStatus', (), IcePy._t_int),
        ('result', (), IcePy._t_int)
    ))

    _M_com.fastonz.fmserver.model.FrontStartModel = FrontStartModel
    del FrontStartModel

# End of module com.fastonz.fmserver.model

__name__ = 'com.fastonz.fmserver'

# End of module com.fastonz.fmserver

__name__ = 'com.fastonz'

# End of module com.fastonz

__name__ = 'com'

# End of module com
