# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.5
#
# <auto-generated>
#
# Generated from file `PhoneGatewayModel.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module com
_M_com = Ice.openModule('com')
__name__ = 'com'

# Start of module com.fastonz
_M_com.fastonz = Ice.openModule('com.fastonz')
__name__ = 'com.fastonz'

# Start of module com.fastonz.fmserver
_M_com.fastonz.fmserver = Ice.openModule('com.fastonz.fmserver')
__name__ = 'com.fastonz.fmserver'

# Start of module com.fastonz.fmserver.model
_M_com.fastonz.fmserver.model = Ice.openModule('com.fastonz.fmserver.model')
__name__ = 'com.fastonz.fmserver.model'

if 'PhoneGatewayModel' not in _M_com.fastonz.fmserver.model.__dict__:
    _M_com.fastonz.fmserver.model.PhoneGatewayModel = Ice.createTempClass()
    class PhoneGatewayModel(object):
        def __init__(self, devID='', serviceAddrs='', verifyCode='', phone='', password='', curOnline=0, maxOnline=0):
            self.devID = devID
            self.serviceAddrs = serviceAddrs
            self.verifyCode = verifyCode
            self.phone = phone
            self.password = password
            self.curOnline = curOnline
            self.maxOnline = maxOnline

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.devID)
            _h = 5 * _h + Ice.getHash(self.serviceAddrs)
            _h = 5 * _h + Ice.getHash(self.verifyCode)
            _h = 5 * _h + Ice.getHash(self.phone)
            _h = 5 * _h + Ice.getHash(self.password)
            _h = 5 * _h + Ice.getHash(self.curOnline)
            _h = 5 * _h + Ice.getHash(self.maxOnline)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_com.fastonz.fmserver.model.PhoneGatewayModel):
                return NotImplemented
            else:
                if self.devID is None or other.devID is None:
                    if self.devID != other.devID:
                        return (-1 if self.devID is None else 1)
                else:
                    if self.devID < other.devID:
                        return -1
                    elif self.devID > other.devID:
                        return 1
                if self.serviceAddrs is None or other.serviceAddrs is None:
                    if self.serviceAddrs != other.serviceAddrs:
                        return (-1 if self.serviceAddrs is None else 1)
                else:
                    if self.serviceAddrs < other.serviceAddrs:
                        return -1
                    elif self.serviceAddrs > other.serviceAddrs:
                        return 1
                if self.verifyCode is None or other.verifyCode is None:
                    if self.verifyCode != other.verifyCode:
                        return (-1 if self.verifyCode is None else 1)
                else:
                    if self.verifyCode < other.verifyCode:
                        return -1
                    elif self.verifyCode > other.verifyCode:
                        return 1
                if self.phone is None or other.phone is None:
                    if self.phone != other.phone:
                        return (-1 if self.phone is None else 1)
                else:
                    if self.phone < other.phone:
                        return -1
                    elif self.phone > other.phone:
                        return 1
                if self.password is None or other.password is None:
                    if self.password != other.password:
                        return (-1 if self.password is None else 1)
                else:
                    if self.password < other.password:
                        return -1
                    elif self.password > other.password:
                        return 1
                if self.curOnline is None or other.curOnline is None:
                    if self.curOnline != other.curOnline:
                        return (-1 if self.curOnline is None else 1)
                else:
                    if self.curOnline < other.curOnline:
                        return -1
                    elif self.curOnline > other.curOnline:
                        return 1
                if self.maxOnline is None or other.maxOnline is None:
                    if self.maxOnline != other.maxOnline:
                        return (-1 if self.maxOnline is None else 1)
                else:
                    if self.maxOnline < other.maxOnline:
                        return -1
                    elif self.maxOnline > other.maxOnline:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_com.fastonz.fmserver.model._t_PhoneGatewayModel)

        __repr__ = __str__

    _M_com.fastonz.fmserver.model._t_PhoneGatewayModel = IcePy.defineStruct('::com::fastonz::fmserver::model::PhoneGatewayModel', PhoneGatewayModel, (), (
        ('devID', (), IcePy._t_string),
        ('serviceAddrs', (), IcePy._t_string),
        ('verifyCode', (), IcePy._t_string),
        ('phone', (), IcePy._t_string),
        ('password', (), IcePy._t_string),
        ('curOnline', (), IcePy._t_int),
        ('maxOnline', (), IcePy._t_int)
    ))

    _M_com.fastonz.fmserver.model.PhoneGatewayModel = PhoneGatewayModel
    del PhoneGatewayModel

# End of module com.fastonz.fmserver.model

__name__ = 'com.fastonz.fmserver'

# End of module com.fastonz.fmserver

__name__ = 'com.fastonz'

# End of module com.fastonz

__name__ = 'com'

# End of module com
