# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.5
#
# <auto-generated>
#
# Generated from file `RoomRouteModel.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module com
_M_com = Ice.openModule('com')
__name__ = 'com'

# Start of module com.fastonz
_M_com.fastonz = Ice.openModule('com.fastonz')
__name__ = 'com.fastonz'

# Start of module com.fastonz.fmserver
_M_com.fastonz.fmserver = Ice.openModule('com.fastonz.fmserver')
__name__ = 'com.fastonz.fmserver'

# Start of module com.fastonz.fmserver.model
_M_com.fastonz.fmserver.model = Ice.openModule('com.fastonz.fmserver.model')
__name__ = 'com.fastonz.fmserver.model'

if 'RoomRouteModel' not in _M_com.fastonz.fmserver.model.__dict__:
    _M_com.fastonz.fmserver.model.RoomRouteModel = Ice.createTempClass()
    class RoomRouteModel(object):
        def __init__(self, roomSrvNodeID='', roomID=0, srvNodeID='', roomNodeID='', srvAuthCode='', srvAppID=0, parentSrvNodeID='', parentSrvAddr='', parentAuthCode='', parentSrvAppID=0):
            self.roomSrvNodeID = roomSrvNodeID
            self.roomID = roomID
            self.srvNodeID = srvNodeID
            self.roomNodeID = roomNodeID
            self.srvAuthCode = srvAuthCode
            self.srvAppID = srvAppID
            self.parentSrvNodeID = parentSrvNodeID
            self.parentSrvAddr = parentSrvAddr
            self.parentAuthCode = parentAuthCode
            self.parentSrvAppID = parentSrvAppID

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.roomSrvNodeID)
            _h = 5 * _h + Ice.getHash(self.roomID)
            _h = 5 * _h + Ice.getHash(self.srvNodeID)
            _h = 5 * _h + Ice.getHash(self.roomNodeID)
            _h = 5 * _h + Ice.getHash(self.srvAuthCode)
            _h = 5 * _h + Ice.getHash(self.srvAppID)
            _h = 5 * _h + Ice.getHash(self.parentSrvNodeID)
            _h = 5 * _h + Ice.getHash(self.parentSrvAddr)
            _h = 5 * _h + Ice.getHash(self.parentAuthCode)
            _h = 5 * _h + Ice.getHash(self.parentSrvAppID)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_com.fastonz.fmserver.model.RoomRouteModel):
                return NotImplemented
            else:
                if self.roomSrvNodeID is None or other.roomSrvNodeID is None:
                    if self.roomSrvNodeID != other.roomSrvNodeID:
                        return (-1 if self.roomSrvNodeID is None else 1)
                else:
                    if self.roomSrvNodeID < other.roomSrvNodeID:
                        return -1
                    elif self.roomSrvNodeID > other.roomSrvNodeID:
                        return 1
                if self.roomID is None or other.roomID is None:
                    if self.roomID != other.roomID:
                        return (-1 if self.roomID is None else 1)
                else:
                    if self.roomID < other.roomID:
                        return -1
                    elif self.roomID > other.roomID:
                        return 1
                if self.srvNodeID is None or other.srvNodeID is None:
                    if self.srvNodeID != other.srvNodeID:
                        return (-1 if self.srvNodeID is None else 1)
                else:
                    if self.srvNodeID < other.srvNodeID:
                        return -1
                    elif self.srvNodeID > other.srvNodeID:
                        return 1
                if self.roomNodeID is None or other.roomNodeID is None:
                    if self.roomNodeID != other.roomNodeID:
                        return (-1 if self.roomNodeID is None else 1)
                else:
                    if self.roomNodeID < other.roomNodeID:
                        return -1
                    elif self.roomNodeID > other.roomNodeID:
                        return 1
                if self.srvAuthCode is None or other.srvAuthCode is None:
                    if self.srvAuthCode != other.srvAuthCode:
                        return (-1 if self.srvAuthCode is None else 1)
                else:
                    if self.srvAuthCode < other.srvAuthCode:
                        return -1
                    elif self.srvAuthCode > other.srvAuthCode:
                        return 1
                if self.srvAppID is None or other.srvAppID is None:
                    if self.srvAppID != other.srvAppID:
                        return (-1 if self.srvAppID is None else 1)
                else:
                    if self.srvAppID < other.srvAppID:
                        return -1
                    elif self.srvAppID > other.srvAppID:
                        return 1
                if self.parentSrvNodeID is None or other.parentSrvNodeID is None:
                    if self.parentSrvNodeID != other.parentSrvNodeID:
                        return (-1 if self.parentSrvNodeID is None else 1)
                else:
                    if self.parentSrvNodeID < other.parentSrvNodeID:
                        return -1
                    elif self.parentSrvNodeID > other.parentSrvNodeID:
                        return 1
                if self.parentSrvAddr is None or other.parentSrvAddr is None:
                    if self.parentSrvAddr != other.parentSrvAddr:
                        return (-1 if self.parentSrvAddr is None else 1)
                else:
                    if self.parentSrvAddr < other.parentSrvAddr:
                        return -1
                    elif self.parentSrvAddr > other.parentSrvAddr:
                        return 1
                if self.parentAuthCode is None or other.parentAuthCode is None:
                    if self.parentAuthCode != other.parentAuthCode:
                        return (-1 if self.parentAuthCode is None else 1)
                else:
                    if self.parentAuthCode < other.parentAuthCode:
                        return -1
                    elif self.parentAuthCode > other.parentAuthCode:
                        return 1
                if self.parentSrvAppID is None or other.parentSrvAppID is None:
                    if self.parentSrvAppID != other.parentSrvAppID:
                        return (-1 if self.parentSrvAppID is None else 1)
                else:
                    if self.parentSrvAppID < other.parentSrvAppID:
                        return -1
                    elif self.parentSrvAppID > other.parentSrvAppID:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_com.fastonz.fmserver.model._t_RoomRouteModel)

        __repr__ = __str__

    _M_com.fastonz.fmserver.model._t_RoomRouteModel = IcePy.defineStruct('::com::fastonz::fmserver::model::RoomRouteModel', RoomRouteModel, (), (
        ('roomSrvNodeID', (), IcePy._t_string),
        ('roomID', (), IcePy._t_int),
        ('srvNodeID', (), IcePy._t_string),
        ('roomNodeID', (), IcePy._t_string),
        ('srvAuthCode', (), IcePy._t_string),
        ('srvAppID', (), IcePy._t_int),
        ('parentSrvNodeID', (), IcePy._t_string),
        ('parentSrvAddr', (), IcePy._t_string),
        ('parentAuthCode', (), IcePy._t_string),
        ('parentSrvAppID', (), IcePy._t_int)
    ))

    _M_com.fastonz.fmserver.model.RoomRouteModel = RoomRouteModel
    del RoomRouteModel

# End of module com.fastonz.fmserver.model

__name__ = 'com.fastonz.fmserver'

# End of module com.fastonz.fmserver

__name__ = 'com.fastonz'

# End of module com.fastonz

__name__ = 'com'

# End of module com
