# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.5
#
# <auto-generated>
#
# Generated from file `RoomCompanyIDBaseModel.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module com
_M_com = Ice.openModule('com')
__name__ = 'com'

# Start of module com.fastonz
_M_com.fastonz = Ice.openModule('com.fastonz')
__name__ = 'com.fastonz'

# Start of module com.fastonz.fmserver
_M_com.fastonz.fmserver = Ice.openModule('com.fastonz.fmserver')
__name__ = 'com.fastonz.fmserver'

# Start of module com.fastonz.fmserver.model
_M_com.fastonz.fmserver.model = Ice.openModule('com.fastonz.fmserver.model')
__name__ = 'com.fastonz.fmserver.model'

if 'RoomCompanyIDBaseModel' not in _M_com.fastonz.fmserver.model.__dict__:
    _M_com.fastonz.fmserver.model.RoomCompanyIDBaseModel = Ice.createTempClass()
    class RoomCompanyIDBaseModel(object):
        def __init__(self, companyID=0, servicesID=0, result=0):
            self.companyID = companyID
            self.servicesID = servicesID
            self.result = result

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.companyID)
            _h = 5 * _h + Ice.getHash(self.servicesID)
            _h = 5 * _h + Ice.getHash(self.result)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_com.fastonz.fmserver.model.RoomCompanyIDBaseModel):
                return NotImplemented
            else:
                if self.companyID is None or other.companyID is None:
                    if self.companyID != other.companyID:
                        return (-1 if self.companyID is None else 1)
                else:
                    if self.companyID < other.companyID:
                        return -1
                    elif self.companyID > other.companyID:
                        return 1
                if self.servicesID is None or other.servicesID is None:
                    if self.servicesID != other.servicesID:
                        return (-1 if self.servicesID is None else 1)
                else:
                    if self.servicesID < other.servicesID:
                        return -1
                    elif self.servicesID > other.servicesID:
                        return 1
                if self.result is None or other.result is None:
                    if self.result != other.result:
                        return (-1 if self.result is None else 1)
                else:
                    if self.result < other.result:
                        return -1
                    elif self.result > other.result:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_com.fastonz.fmserver.model._t_RoomCompanyIDBaseModel)

        __repr__ = __str__

    _M_com.fastonz.fmserver.model._t_RoomCompanyIDBaseModel = IcePy.defineStruct('::com::fastonz::fmserver::model::RoomCompanyIDBaseModel', RoomCompanyIDBaseModel, (), (
        ('companyID', (), IcePy._t_int),
        ('servicesID', (), IcePy._t_int),
        ('result', (), IcePy._t_int)
    ))

    _M_com.fastonz.fmserver.model.RoomCompanyIDBaseModel = RoomCompanyIDBaseModel
    del RoomCompanyIDBaseModel

# End of module com.fastonz.fmserver.model

__name__ = 'com.fastonz.fmserver'

# End of module com.fastonz.fmserver

__name__ = 'com.fastonz'

# End of module com.fastonz

__name__ = 'com'

# End of module com
