# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.5
#
# <auto-generated>
#
# Generated from file `TerminalConnInfoModel.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module com
_M_com = Ice.openModule('com')
__name__ = 'com'

# Start of module com.fastonz
_M_com.fastonz = Ice.openModule('com.fastonz')
__name__ = 'com.fastonz'

# Start of module com.fastonz.fmserver
_M_com.fastonz.fmserver = Ice.openModule('com.fastonz.fmserver')
__name__ = 'com.fastonz.fmserver'

# Start of module com.fastonz.fmserver.model
_M_com.fastonz.fmserver.model = Ice.openModule('com.fastonz.fmserver.model')
__name__ = 'com.fastonz.fmserver.model'

if 'TerminalConnInfoModel' not in _M_com.fastonz.fmserver.model.__dict__:
    _M_com.fastonz.fmserver.model.TerminalConnInfoModel = Ice.createTempClass()
    class TerminalConnInfoModel(object):
        def __init__(self, terminalID='', terminalName='', activeSrvAddr=''):
            self.terminalID = terminalID
            self.terminalName = terminalName
            self.activeSrvAddr = activeSrvAddr

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.terminalID)
            _h = 5 * _h + Ice.getHash(self.terminalName)
            _h = 5 * _h + Ice.getHash(self.activeSrvAddr)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_com.fastonz.fmserver.model.TerminalConnInfoModel):
                return NotImplemented
            else:
                if self.terminalID is None or other.terminalID is None:
                    if self.terminalID != other.terminalID:
                        return (-1 if self.terminalID is None else 1)
                else:
                    if self.terminalID < other.terminalID:
                        return -1
                    elif self.terminalID > other.terminalID:
                        return 1
                if self.terminalName is None or other.terminalName is None:
                    if self.terminalName != other.terminalName:
                        return (-1 if self.terminalName is None else 1)
                else:
                    if self.terminalName < other.terminalName:
                        return -1
                    elif self.terminalName > other.terminalName:
                        return 1
                if self.activeSrvAddr is None or other.activeSrvAddr is None:
                    if self.activeSrvAddr != other.activeSrvAddr:
                        return (-1 if self.activeSrvAddr is None else 1)
                else:
                    if self.activeSrvAddr < other.activeSrvAddr:
                        return -1
                    elif self.activeSrvAddr > other.activeSrvAddr:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_com.fastonz.fmserver.model._t_TerminalConnInfoModel)

        __repr__ = __str__

    _M_com.fastonz.fmserver.model._t_TerminalConnInfoModel = IcePy.defineStruct('::com::fastonz::fmserver::model::TerminalConnInfoModel', TerminalConnInfoModel, (), (
        ('terminalID', (), IcePy._t_string),
        ('terminalName', (), IcePy._t_string),
        ('activeSrvAddr', (), IcePy._t_string)
    ))

    _M_com.fastonz.fmserver.model.TerminalConnInfoModel = TerminalConnInfoModel
    del TerminalConnInfoModel

# End of module com.fastonz.fmserver.model

__name__ = 'com.fastonz.fmserver'

# End of module com.fastonz.fmserver

__name__ = 'com.fastonz'

# End of module com.fastonz

__name__ = 'com'

# End of module com
