# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.5
#
# <auto-generated>
#
# Generated from file `UpdateDeviceModel.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module com
_M_com = Ice.openModule('com')
__name__ = 'com'

# Start of module com.fastonz
_M_com.fastonz = Ice.openModule('com.fastonz')
__name__ = 'com.fastonz'

# Start of module com.fastonz.fmserver
_M_com.fastonz.fmserver = Ice.openModule('com.fastonz.fmserver')
__name__ = 'com.fastonz.fmserver'

# Start of module com.fastonz.fmserver.model
_M_com.fastonz.fmserver.model = Ice.openModule('com.fastonz.fmserver.model')
__name__ = 'com.fastonz.fmserver.model'

if 'UpdateDeviceModel' not in _M_com.fastonz.fmserver.model.__dict__:
    _M_com.fastonz.fmserver.model.UpdateDeviceModel = Ice.createTempClass()
    class UpdateDeviceModel(object):
        def __init__(self, deviceID='', verifyCode='', onlines=0, bandWidth=0, roomCount=0, CPULoad=0):
            self.deviceID = deviceID
            self.verifyCode = verifyCode
            self.onlines = onlines
            self.bandWidth = bandWidth
            self.roomCount = roomCount
            self.CPULoad = CPULoad

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.deviceID)
            _h = 5 * _h + Ice.getHash(self.verifyCode)
            _h = 5 * _h + Ice.getHash(self.onlines)
            _h = 5 * _h + Ice.getHash(self.bandWidth)
            _h = 5 * _h + Ice.getHash(self.roomCount)
            _h = 5 * _h + Ice.getHash(self.CPULoad)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_com.fastonz.fmserver.model.UpdateDeviceModel):
                return NotImplemented
            else:
                if self.deviceID is None or other.deviceID is None:
                    if self.deviceID != other.deviceID:
                        return (-1 if self.deviceID is None else 1)
                else:
                    if self.deviceID < other.deviceID:
                        return -1
                    elif self.deviceID > other.deviceID:
                        return 1
                if self.verifyCode is None or other.verifyCode is None:
                    if self.verifyCode != other.verifyCode:
                        return (-1 if self.verifyCode is None else 1)
                else:
                    if self.verifyCode < other.verifyCode:
                        return -1
                    elif self.verifyCode > other.verifyCode:
                        return 1
                if self.onlines is None or other.onlines is None:
                    if self.onlines != other.onlines:
                        return (-1 if self.onlines is None else 1)
                else:
                    if self.onlines < other.onlines:
                        return -1
                    elif self.onlines > other.onlines:
                        return 1
                if self.bandWidth is None or other.bandWidth is None:
                    if self.bandWidth != other.bandWidth:
                        return (-1 if self.bandWidth is None else 1)
                else:
                    if self.bandWidth < other.bandWidth:
                        return -1
                    elif self.bandWidth > other.bandWidth:
                        return 1
                if self.roomCount is None or other.roomCount is None:
                    if self.roomCount != other.roomCount:
                        return (-1 if self.roomCount is None else 1)
                else:
                    if self.roomCount < other.roomCount:
                        return -1
                    elif self.roomCount > other.roomCount:
                        return 1
                if self.CPULoad is None or other.CPULoad is None:
                    if self.CPULoad != other.CPULoad:
                        return (-1 if self.CPULoad is None else 1)
                else:
                    if self.CPULoad < other.CPULoad:
                        return -1
                    elif self.CPULoad > other.CPULoad:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_com.fastonz.fmserver.model._t_UpdateDeviceModel)

        __repr__ = __str__

    _M_com.fastonz.fmserver.model._t_UpdateDeviceModel = IcePy.defineStruct('::com::fastonz::fmserver::model::UpdateDeviceModel', UpdateDeviceModel, (), (
        ('deviceID', (), IcePy._t_string),
        ('verifyCode', (), IcePy._t_string),
        ('onlines', (), IcePy._t_int),
        ('bandWidth', (), IcePy._t_int),
        ('roomCount', (), IcePy._t_int),
        ('CPULoad', (), IcePy._t_int)
    ))

    _M_com.fastonz.fmserver.model.UpdateDeviceModel = UpdateDeviceModel
    del UpdateDeviceModel

# End of module com.fastonz.fmserver.model

__name__ = 'com.fastonz.fmserver'

# End of module com.fastonz.fmserver

__name__ = 'com.fastonz'

# End of module com.fastonz

__name__ = 'com'

# End of module com
