# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.5
#
# <auto-generated>
#
# Generated from file `UpdateRoomCurDevModel.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module com
_M_com = Ice.openModule('com')
__name__ = 'com'

# Start of module com.fastonz
_M_com.fastonz = Ice.openModule('com.fastonz')
__name__ = 'com.fastonz'

# Start of module com.fastonz.fmserver
_M_com.fastonz.fmserver = Ice.openModule('com.fastonz.fmserver')
__name__ = 'com.fastonz.fmserver'

# Start of module com.fastonz.fmserver.model
_M_com.fastonz.fmserver.model = Ice.openModule('com.fastonz.fmserver.model')
__name__ = 'com.fastonz.fmserver.model'

if 'UpdateRoomCurDevModel' not in _M_com.fastonz.fmserver.model.__dict__:
    _M_com.fastonz.fmserver.model.UpdateRoomCurDevModel = Ice.createTempClass()
    class UpdateRoomCurDevModel(object):
        def __init__(self, roomNodeID='', roomID=0, roomAppID=0, roomMaxUserCount=0, roomDevID=''):
            self.roomNodeID = roomNodeID
            self.roomID = roomID
            self.roomAppID = roomAppID
            self.roomMaxUserCount = roomMaxUserCount
            self.roomDevID = roomDevID

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.roomNodeID)
            _h = 5 * _h + Ice.getHash(self.roomID)
            _h = 5 * _h + Ice.getHash(self.roomAppID)
            _h = 5 * _h + Ice.getHash(self.roomMaxUserCount)
            _h = 5 * _h + Ice.getHash(self.roomDevID)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_com.fastonz.fmserver.model.UpdateRoomCurDevModel):
                return NotImplemented
            else:
                if self.roomNodeID is None or other.roomNodeID is None:
                    if self.roomNodeID != other.roomNodeID:
                        return (-1 if self.roomNodeID is None else 1)
                else:
                    if self.roomNodeID < other.roomNodeID:
                        return -1
                    elif self.roomNodeID > other.roomNodeID:
                        return 1
                if self.roomID is None or other.roomID is None:
                    if self.roomID != other.roomID:
                        return (-1 if self.roomID is None else 1)
                else:
                    if self.roomID < other.roomID:
                        return -1
                    elif self.roomID > other.roomID:
                        return 1
                if self.roomAppID is None or other.roomAppID is None:
                    if self.roomAppID != other.roomAppID:
                        return (-1 if self.roomAppID is None else 1)
                else:
                    if self.roomAppID < other.roomAppID:
                        return -1
                    elif self.roomAppID > other.roomAppID:
                        return 1
                if self.roomMaxUserCount is None or other.roomMaxUserCount is None:
                    if self.roomMaxUserCount != other.roomMaxUserCount:
                        return (-1 if self.roomMaxUserCount is None else 1)
                else:
                    if self.roomMaxUserCount < other.roomMaxUserCount:
                        return -1
                    elif self.roomMaxUserCount > other.roomMaxUserCount:
                        return 1
                if self.roomDevID is None or other.roomDevID is None:
                    if self.roomDevID != other.roomDevID:
                        return (-1 if self.roomDevID is None else 1)
                else:
                    if self.roomDevID < other.roomDevID:
                        return -1
                    elif self.roomDevID > other.roomDevID:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_com.fastonz.fmserver.model._t_UpdateRoomCurDevModel)

        __repr__ = __str__

    _M_com.fastonz.fmserver.model._t_UpdateRoomCurDevModel = IcePy.defineStruct('::com::fastonz::fmserver::model::UpdateRoomCurDevModel', UpdateRoomCurDevModel, (), (
        ('roomNodeID', (), IcePy._t_string),
        ('roomID', (), IcePy._t_int),
        ('roomAppID', (), IcePy._t_int),
        ('roomMaxUserCount', (), IcePy._t_int),
        ('roomDevID', (), IcePy._t_string)
    ))

    _M_com.fastonz.fmserver.model.UpdateRoomCurDevModel = UpdateRoomCurDevModel
    del UpdateRoomCurDevModel

# End of module com.fastonz.fmserver.model

__name__ = 'com.fastonz.fmserver'

# End of module com.fastonz.fmserver

__name__ = 'com.fastonz'

# End of module com.fastonz

__name__ = 'com'

# End of module com
