# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.5
#
# <auto-generated>
#
# Generated from file `VerifyRoomUserRequestModel2.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module com
_M_com = Ice.openModule('com')
__name__ = 'com'

# Start of module com.fastonz
_M_com.fastonz = Ice.openModule('com.fastonz')
__name__ = 'com.fastonz'

# Start of module com.fastonz.fmserver
_M_com.fastonz.fmserver = Ice.openModule('com.fastonz.fmserver')
__name__ = 'com.fastonz.fmserver'

# Start of module com.fastonz.fmserver.model
_M_com.fastonz.fmserver.model = Ice.openModule('com.fastonz.fmserver.model')
__name__ = 'com.fastonz.fmserver.model'

if 'VerifyRoomUserRequestModel2' not in _M_com.fastonz.fmserver.model.__dict__:
    _M_com.fastonz.fmserver.model.VerifyRoomUserRequestModel2 = Ice.createTempClass()
    class VerifyRoomUserRequestModel2(object):
        def __init__(self, roomID=0, unameType=0, userID=0, checkPwd=0, terminalType=0, roomPassword=''):
            self.roomID = roomID
            self.unameType = unameType
            self.userID = userID
            self.checkPwd = checkPwd
            self.terminalType = terminalType
            self.roomPassword = roomPassword

        def __hash__(self):
            _h = 0
            _h = 5 * _h + Ice.getHash(self.roomID)
            _h = 5 * _h + Ice.getHash(self.unameType)
            _h = 5 * _h + Ice.getHash(self.userID)
            _h = 5 * _h + Ice.getHash(self.checkPwd)
            _h = 5 * _h + Ice.getHash(self.terminalType)
            _h = 5 * _h + Ice.getHash(self.roomPassword)
            return _h % 0x7fffffff

        def __compare(self, other):
            if other is None:
                return 1
            elif not isinstance(other, _M_com.fastonz.fmserver.model.VerifyRoomUserRequestModel2):
                return NotImplemented
            else:
                if self.roomID is None or other.roomID is None:
                    if self.roomID != other.roomID:
                        return (-1 if self.roomID is None else 1)
                else:
                    if self.roomID < other.roomID:
                        return -1
                    elif self.roomID > other.roomID:
                        return 1
                if self.unameType is None or other.unameType is None:
                    if self.unameType != other.unameType:
                        return (-1 if self.unameType is None else 1)
                else:
                    if self.unameType < other.unameType:
                        return -1
                    elif self.unameType > other.unameType:
                        return 1
                if self.userID is None or other.userID is None:
                    if self.userID != other.userID:
                        return (-1 if self.userID is None else 1)
                else:
                    if self.userID < other.userID:
                        return -1
                    elif self.userID > other.userID:
                        return 1
                if self.checkPwd is None or other.checkPwd is None:
                    if self.checkPwd != other.checkPwd:
                        return (-1 if self.checkPwd is None else 1)
                else:
                    if self.checkPwd < other.checkPwd:
                        return -1
                    elif self.checkPwd > other.checkPwd:
                        return 1
                if self.terminalType is None or other.terminalType is None:
                    if self.terminalType != other.terminalType:
                        return (-1 if self.terminalType is None else 1)
                else:
                    if self.terminalType < other.terminalType:
                        return -1
                    elif self.terminalType > other.terminalType:
                        return 1
                if self.roomPassword is None or other.roomPassword is None:
                    if self.roomPassword != other.roomPassword:
                        return (-1 if self.roomPassword is None else 1)
                else:
                    if self.roomPassword < other.roomPassword:
                        return -1
                    elif self.roomPassword > other.roomPassword:
                        return 1
                return 0

        def __lt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r < 0

        def __le__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r <= 0

        def __gt__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r > 0

        def __ge__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r >= 0

        def __eq__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r == 0

        def __ne__(self, other):
            r = self.__compare(other)
            if r is NotImplemented:
                return r
            else:
                return r != 0

        def __str__(self):
            return IcePy.stringify(self, _M_com.fastonz.fmserver.model._t_VerifyRoomUserRequestModel2)

        __repr__ = __str__

    _M_com.fastonz.fmserver.model._t_VerifyRoomUserRequestModel2 = IcePy.defineStruct('::com::fastonz::fmserver::model::VerifyRoomUserRequestModel2', VerifyRoomUserRequestModel2, (), (
        ('roomID', (), IcePy._t_int),
        ('unameType', (), IcePy._t_int),
        ('userID', (), IcePy._t_int),
        ('checkPwd', (), IcePy._t_int),
        ('terminalType', (), IcePy._t_int),
        ('roomPassword', (), IcePy._t_string)
    ))

    _M_com.fastonz.fmserver.model.VerifyRoomUserRequestModel2 = VerifyRoomUserRequestModel2
    del VerifyRoomUserRequestModel2

# End of module com.fastonz.fmserver.model

__name__ = 'com.fastonz.fmserver'

# End of module com.fastonz.fmserver

__name__ = 'com.fastonz'

# End of module com.fastonz

__name__ = 'com'

# End of module com
