# Generated by slice2py - DO NOT EDIT!
#

import Ice
Ice.updateModule("com.fastonz.loadSrv")

# Modules:
import LoadHeartbeatModel_ice
import LoadModel_ice
import LoadService_ice

# Submodules:
from . import model
from . import controller
