# Generated by slice2py - DO NOT EDIT!
#

import Ice
Ice.updateModule("com.fastonz.fmconfctlserver.model")

# Modules:
import CloseRoomRequestModel_ice
import CloseRoomResponseModel_ice

# Submodules:
